spring.application.name=10_SB_CROUD_APP


spring.datasource.url=jdbc:mysql://localhost:3306/testdb
spring.datasource.username=root
spring.datasource.password=9928

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true